# CUDA_VISIBLE_DEVICES=0,1 python create_heatmaps_production_surv.py --config_file heatmap_config_gbmlgg_surv_test_20x.yaml
--- 
exp_arguments:
  # which split
  split: 5foldcv_lung_omic
  # which experiment
  #exp: test_1_WSI_a0.6_reg1e-06_10foldcv_mad_FLAIR,T1,T2,T1Gd
  # number of classes
  n_classes: 4
  # what to call experiment 
  save_exp_code: lung_omics_5fold_luad
  # where to save intermediate/raw results
  raw_save_dir: heatmap_raw_results/lung
  # where to save final results
  production_save_dir: heatmap_production_results/lung
  batch_size: 64
  # bins defining risk scores (can also set to null)
  bins: null
data_arguments: 
  data_dir: /mnt/sdb1/Dataset/lung/Radiology
  data_h5_dir: /mnt/sdb1/all_features/features/lung/radio_h5_files
  process_list: samples_luad.csv # list of slides to process
  preset: process_list_autogen.csv # preset for segmentation/filter parameters
  slide_ext: .svs
  cancer_type: lung
patching_arguments:
  patch_size: 256 
  overlap: 0.75 # overlap for patching
  patch_level: 0 # downsample of WSI at which to patch from 
   #if > 1, patches of size patch_size * custom_downsample are extracted and downscaled to patch_sizes
  custom_downsample: 2 
model_arguments: 
  model_path: /mnt/sdb1/integrated_multimodal_fusion/results/lung/5foldcv_lung_omic/OMICS_a0.6_reg1e-02_s0
  pkl_path: null
  #/mnt/sdb1/integrated_multimodal_fusion/results/brain/10foldcv_gbmlgg_german_omics_pretrained/OMICS_cox_surv_a0.0_reg1e-04_highway_nl8_s0
  cv: 2
  model_type: max_net
  mode: omics
  initiate_fn: initiate_model
  model_size_omic: small
  bag_loss: cox_surv
  drop_out: true
  n_classes: 4
  alpha_surv: 0.6
  transfer: false
  split_mode: train_val
  task: lung_5_dataset
  modalities:
    - CT
  
heatmap_arguments:
  # downsample at which to visualize heatmap (-1 refers to downsample closest to 32x downsample)
  vis_level: -1
  # transparency for overlaying heatmap on background (0: background only, 1: foreground only)
  alpha: 0.3
  #0.3
  # whether to use a blank canvas instead of original slide
  blank_canvas: false
  # whether to also save the original H&E image
  save_orig: true
  # file extension for saving heatmap/original image
  save_ext: jpg
  # whether to calculate percentile scores in reference to the set of non-overlapping patches
  use_ref_scores: false
  # whether to use gaussian blur for further smoothing
  blur: false 
  # whether to shift the 4 default points for checking if a patch is inside a foreground contour
  use_center_shift: true
  # whether to only compute heatmap for ROI specified by x1, x2, y1, y2
  use_roi: false 
  # whether to calculate heatmap with specified overlap (by default, coarse heatmap without overlap is always calculated)
  calc_heatmap: true
  # whether to binarize attention scores
  binarize: false
  # binarization threshold: (0, 1)
  binary_thresh: -1
  custom_downsample: 1
  #2
sample_arguments: 
  # arguments for sampling patches
  samples:
    - name: "topk_high_attention"
      sample: true
      seed: 1
      k: 10
      mode: topk
    - name: "topk_low_attention"
      sample: true
      seed: 1
      k: 10
      mode: reverse_topk
