# CUDA_VISIBLE_DEVICES=0,1 python create_heatmaps_production_surv.py --config_file heatmap_config_gbmlgg_surv_test_20x.yaml
--- 
exp_arguments:
  # which split
  split: 5foldcv_gbmlgg_german_omics_path
  # which experiment
  #exp: test_1_WSI_a0.6_reg1e-06_10foldcv_mad_FLAIR,T1,T2,T1Gd
  # number of classes
  n_classes: 8
  # what to call experiment 
  save_exp_code: brain_path_german_omics
  # where to save intermediate/raw results
  raw_save_dir: heatmap_raw_results/brain
  # where to save final results
  production_save_dir: heatmap_production_results/brain
  batch_size: 64
  # bins defining risk scores (can also set to null)
  bins: null
data_arguments: 
  data_dir: /mnt/sdb1/Dataset/brain/Pathology/slides
  mask_dir: /mnt/sdb1/Dataset/brain/Pathology/masks
  data_h5_dir: /mnt/sdb1/integrated_multimodal_fusion/features/brain/path_h5_files
  process_list: samples_german_omics.csv # list of slides to process
  preset: process_list_autogen.csv # preset for segmentation/filter parameters
  slide_ext: .svs
  cancer_type: brain
patching_arguments:
  patch_size: 256
  overlap: 0.75 # overlap for patching
  patch_level: 0 # downsample of WSI at which to patch from 
   #if > 1, patches of size patch_size * custom_downsample are extracted and downscaled to patch_sizes
  custom_downsample: 2 
model_arguments: 
  model_path: /mnt/sdb1/integrated_multimodal_fusion/results/brain/5foldcv_gbmlgg_german_omics_path/PATH_a0.6_s0
  pkl_path: null
  #/mnt/sdb1/integrated_multimodal_fusion/results/brain/10foldcv_gbmlgg_german_omics_pretrained/PATH_ranking_surv_a0.0_reg1e-04_highway_nl8_s0
  cv: 1
  #/mnt/sda1/Lottie/histopathology_gbmlgg/fusion_glioma/results/10foldcv_169/test_4_MMF_g000_a0.6_reg1e-06_10foldcv_mad_FLAIR,T1,T2,T1Gd/test_4_MMF_g000_a0.6_reg1e-06_10foldcv_mad_FLAIR,T1,T2,T1Gd_s0/s_5_minloss_checkpoint.pt
  model_type: path_attention_mil
  mode: path
  initiate_fn: initiate_model
  model_size_wsi: small
  drop_out: true
  n_classes: 8
  alpha_surv: 0.6
  transfer: false
  split_mode: train_val
  task: gbmlgg_survival_german_omics
  modalities:
    - T1
    - T2
    - T1Gd
    - FLAIR
heatmap_arguments:
  # downsample at which to visualize heatmap (-1 refers to downsample closest to 32x downsample)
  vis_level: -1
  # transparency for overlaying heatmap on background (0: background only, 1: foreground only)
  alpha: 0.65
  #0.3
  # whether to use a blank canvas instead of original slide
  blank_canvas: false
  # whether to also save the original H&E image
  save_orig: true
  # file extension for saving heatmap/original image
  save_ext: jpg
  # whether to calculate percentile scores in reference to the set of non-overlapping patches
  use_ref_scores: false
  # whether to use gaussian blur for further smoothing
  blur: false 
  # whether to shift the 4 default points for checking if a patch is inside a foreground contour
  use_center_shift: true
  # whether to only compute heatmap for ROI specified by x1, x2, y1, y2
  use_roi: false 
  # whether to calculate heatmap with specified overlap (by default, coarse heatmap without overlap is always calculated)
  calc_heatmap: true
  # whether to binarize attention scores
  binarize: false
  # binarization threshold: (0, 1)
  binary_thresh: -1
  custom_downsample: 1
  #2
sample_arguments: 
  # arguments for sampling patches
  samples:
    - name: "topk_high_attention"
      sample: true
      seed: 1
      k: 10
      mode: topk
    - name: "topk_low_attention"
      sample: true
      seed: 1
      k: 3
      mode: reverse_topk
